name: Miniexact Page
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: emscripten/emsdk:3.1.44
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ github.event.inputs.checkoutRef }}
      - name: Create Build Folder
        run: mkdir build-emscripten
      - name: Configure with CMake
        run: emcmake cmake -Bbuild-emscripten -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: make -C build-emscripten
      - name: Copy built files to web folder
        run: cp build-emscripten/miniexactsolve.js build-emscripten/miniexactsolve.wasm web/
      - name: Install rsync for GitHub Page Deploy Action
        run: sudo apt update && sudo apt install -y rsync
      - name: Deploy Page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web
