name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/miniexact
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Build package
        run: |
          pip wheel -w dist .
      - name: Remove superflous cmeel package
        run: rm dist/cmeel*
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1